package com.stzteam.features.advantagekitbridge;

import org.littletonrobotics.junction.LogTable;
import org.littletonrobotics.junction.inputs.LoggableInputs;

import com.stzteam.features.advantagekitbridge.internal.BridgeLog;
import com.stzteam.features.advantagekitbridge.internal.LogCodec;
import com.stzteam.features.advantagekitbridge.internal.LogCodecFactory;

/**
 * Adapts any MARS {@code Data} snapshot into an AdvantageKit {@link LoggableInputs}.
 * <p>
 * This is the piece that makes an existing MARS subsystem loggable and replayable without
 * touching its {@code Data} class. It reuses the exact convention ForgeMini's
 * {@code NetworkIO} already expects -- public fields, with complex types carrying a static
 * {@code Struct} field -- and targets a {@link LogTable} instead of NetworkTables.
 * <p>
 * A {@code Data} class that already implements {@link LoggableInputs} itself (for instance
 * one generated by AdvantageKit's {@code @AutoLog} processor) does not need this adapter;
 * {@link AdvantageKitBridge} detects that and hands the object straight to the logger.
 *
 * <h2>Reuse across loops</h2>
 * The instance is designed to be created once per subsystem and retargeted every cycle via
 * {@link #setTarget(Object)}. MARS calls its input hook once per subsystem per loop, so
 * allocating an adapter there would mean a garbage object per subsystem at 50 Hz.
 *
 * <h2>Threading</h2>
 * Not thread-safe, matching {@code Logger.processInputs}, which must be called from the
 * main robot thread.
 */
public class MarsLoggableInput implements LoggableInputs {

    private final BridgeConfig config;

    private Object target;
    private Class<?> targetClass;
    private LogCodec[] codecs = new LogCodec[0];

    /**
     * Creates an empty adapter using the bridge's active configuration. Call
     * {@link #setTarget(Object)} before handing it to the logger.
     */
    public MarsLoggableInput() {
        this(null, AdvantageKitBridge.getConfig());
    }

    /**
     * Creates an adapter around a data object, using the bridge's active configuration.
     *
     * @param target A MARS {@code Data} snapshot, or any object following the convention.
     */
    public MarsLoggableInput(Object target) {
        this(target, AdvantageKitBridge.getConfig());
    }

    /**
     * Creates an adapter around a data object with an explicit configuration. Useful for
     * logging a one-off structure under different naming rules than the global bridge.
     *
     * @param target A MARS {@code Data} snapshot, or any object following the convention.
     * @param config The configuration controlling key naming and nesting.
     */
    public MarsLoggableInput(Object target, BridgeConfig config) {
        this.config = config;
        setTarget(target);
    }

    /**
     * Points this adapter at a new data object, recompiling the field plan only if the
     * object's class changed.
     *
     * @param target The data object to log or replay into. May be null, in which case
     *               logging and replay become no-ops.
     */
    public final void setTarget(Object target) {
        this.target = target;
        if (target == null) {
            return;
        }
        Class<?> clazz = target.getClass();
        if (clazz != targetClass) {
            targetClass = clazz;
            codecs = LogCodecFactory.forClass(clazz, config);
            if (codecs.length == 0) {
                BridgeLog.warnOnce(
                        clazz.getName() + "#empty",
                        clazz.getSimpleName() + " has no loggable public fields, so it will appear empty "
                                + "in the log. MARS Data classes are expected to expose their inputs as "
                                + "public fields, the same convention ForgeMini publishes from.");
            }
        }
    }

    /** @return The object currently being logged or replayed into, possibly null. */
    public final Object getTarget() {
        return target;
    }

    /** @return The number of fields this adapter moves in and out of the log. */
    public final int getFieldCount() {
        return codecs.length;
    }

    @Override
    public void toLog(LogTable table) {
        if (target == null) {
            return;
        }
        for (LogCodec codec : codecs) {
            try {
                codec.toLog(table, target);
            } catch (IllegalAccessException | RuntimeException e) {
                reportFailure(codec, e, "write");
            }
        }
    }

    @Override
    public void fromLog(LogTable table) {
        if (target == null) {
            return;
        }
        for (LogCodec codec : codecs) {
            try {
                codec.fromLog(table, target);
            } catch (IllegalAccessException | RuntimeException e) {
                reportFailure(codec, e, "read");
            }
        }
    }

    private void reportFailure(LogCodec codec, Exception e, String direction) {
        // One bad field must not take the whole subsystem's inputs down with it: the rest of
        // the snapshot is still worth logging, and on a real field a crash here would be a
        // dead robot rather than a missing chart.
        BridgeLog.errorOnce(
                codec.field().getDeclaringClass().getName() + "." + codec.field().getName() + "#" + direction,
                "Could not " + direction + " field \"" + codec.key() + "\" of "
                        + codec.field().getDeclaringClass().getSimpleName() + ": " + e);
    }
}
